# -*- coding: utf-8 -*-
"""Merging_CSV_Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e2M7NmDu1fh0PIEaypLZcwHd9ZTST1T1
"""

# ───────────────────────────────────────────────
# MERGE VEHICLE FILES + ADD New_VehicleID COLUMN
# (New_VehicleID placed immediately after VehicleID)
# ───────────────────────────────────────────────

import pandas as pd
from google.colab import files
import io

# 1️⃣ Upload any number of CSVs
uploaded = files.upload()          # ⇧ click “Choose Files”

# 2️⃣ Read, tag, and collect
dfs = []
for idx, fname in enumerate(uploaded.keys(), start=1):       # idx = file number
    df = pd.read_csv(io.BytesIO(uploaded[fname]))

    if 'VehicleID' not in df.columns:
        raise ValueError(f"'VehicleID' column missing in {fname}")

    # Append file number to avoid clashes (e.g. Car01_F1, Car01_F2 …)
    df['New_VehicleID'] = df['VehicleID'].astype(str) + f"_F{idx}"

    # Re-order so New_VehicleID sits right after VehicleID
    cols = df.columns.tolist()
    cols.insert(cols.index('VehicleID') + 1, cols.pop(cols.index('New_VehicleID')))
    df = df[cols]

    dfs.append(df)

# 3️⃣ Merge everything
merged_df = pd.concat(dfs, ignore_index=True)

# 4️⃣ Save + download
out_name = "Merged_Vehicles.csv"
merged_df.to_csv(out_name, index=False)
files.download(out_name)