# -*- coding: utf-8 -*-
"""Percentage _Driver_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12NtCFuYrHf-u9IdKXHievEbujq5gNPvs
"""

# 🚀 STEP 1: Install Required Libraries
# You probably already have pandas installed, but if not, uncomment below
# !pip install pandas

# 🚀 STEP 2: Import Libraries
import pandas as pd
from google.colab import files
import io

# 🚀 STEP 3: Upload the CSV file
print("🔹 Please upload your behavior classification CSV file (the one with 'Behavior Class' column):")
uploaded = files.upload()

# Get the uploaded filename
filename = list(uploaded.keys())[0]

# 🚀 STEP 4: Read the CSV into a DataFrame
df = pd.read_csv(io.BytesIO(uploaded[filename]))

# Display the first few rows for verification
print("\n🔹 Preview of your data:")
display(df.head())

# 🚀 STEP 5: Check if 'Behavior Class' column exists
if 'Behavior Class' not in df.columns:
    raise ValueError("❌ The file does not contain a 'Behavior Class' column. Please check your CSV.")

# 🚀 STEP 6: Count the number of vehicles in each class
counts = df['Behavior Class'].value_counts()
total = counts.sum()

# 🚀 STEP 7: Calculate percentages
percentages = (counts / total) * 100

# 🚀 STEP 8: Combine counts and percentages into a summary table
summary_df = pd.DataFrame({
    'Count of Vehicles': counts,
    'Percentage (%)': percentages.round(2)
}).reset_index().rename(columns={'index': 'Behavior Class'})

# 🚀 STEP 9: Display the summary table
print("\n✅ Summary of Behavior Classification:")
display(summary_df)

# 🚀 STEP 10: Print plain text output for clarity
print("\n🔹 Plain text output:")
for i, row in summary_df.iterrows():
    print(f"{row['Behavior Class']}: {row['Count of Vehicles']} vehicles ({row['Percentage (%)']}%)")

# 🚀 STEP 11: (Optional) Save the summary as a CSV
summary_df.to_csv('Behavior_Class_Summary.csv', index=False)
print("\n✅ Summary CSV saved as 'Behavior_Class_Summary.csv'")